-- Package for reconciliation and variance calculation
CREATE OR REPLACE PACKAGE PKG_IAGACK_RECONCILIATION AS
    PROCEDURE VALIDATE_ENTRIES;
    PROCEDURE CALCULATE_VARIANCE;
END PKG_IAGACK_RECONCILIATION;
/

CREATE OR REPLACE PACKAGE BODY PKG_IAGACK_RECONCILIATION AS

    PROCEDURE VALIDATE_ENTRIES IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE('Validating GL and Subledger entries...');
    END;

    PROCEDURE CALCULATE_VARIANCE IS
    BEGIN
        INSERT INTO VARIANCE_LOG (LOG_ID, GL_ENTRY_ID, SUB_ENTRY_ID, VARIANCE, STATUS)
        SELECT SEQ_VAR_LOG.NEXTVAL, g.ENTRY_ID, s.ENTRY_ID,
               g.AMOUNT - s.AMOUNT,
               CASE WHEN g.AMOUNT - s.AMOUNT = 0 THEN 'MATCHED' ELSE 'MISMATCH' END
          FROM GL_ENTRIES g
          JOIN SUBLEDGER_ENTRIES s ON g.ENTRY_ID = s.ENTRY_ID;
        COMMIT;
    END;
END PKG_IAGACK_RECONCILIATION;
/
