-- Finance KPIs and reconciliation summary
-- Total variance by day
SELECT TRUNC(LOG_DATE) AS REPORT_DATE,
       SUM(VARIANCE) AS TOTAL_VARIANCE,
       COUNT(*) AS TOTAL_ENTRIES
FROM VARIANCE_LOG
GROUP BY TRUNC(LOG_DATE)
ORDER BY REPORT_DATE DESC;

-- KPI: Match rate
SELECT ROUND(
    (SUM(CASE WHEN STATUS='MATCHED' THEN 1 ELSE 0 END) / COUNT(*))*100, 2
) AS MATCH_RATE_PERCENT
FROM VARIANCE_LOG;
