-- Core tables for GL/Subledger reconciliation
CREATE TABLE GL_ENTRIES (
    ENTRY_ID NUMBER PRIMARY KEY,
    GL_ACCOUNT VARCHAR2(30),
    AMOUNT NUMBER(15,2),
    ENTRY_DATE DATE,
    SOURCE_SYSTEM VARCHAR2(50)
);

CREATE TABLE SUBLEDGER_ENTRIES (
    ENTRY_ID NUMBER PRIMARY KEY,
    SUB_ACCOUNT VARCHAR2(30),
    AMOUNT NUMBER(15,2),
    ENTRY_DATE DATE,
    SOURCE_SYSTEM VARCHAR2(50)
);

CREATE TABLE VARIANCE_LOG (
    LOG_ID NUMBER PRIMARY KEY,
    GL_ENTRY_ID NUMBER,
    SUB_ENTRY_ID NUMBER,
    VARIANCE NUMBER(15,2),
    STATUS VARCHAR2(20),
    LOG_DATE DATE DEFAULT SYSDATE
);
