-- (Optional) safety drops for dev runs
BEGIN EXECUTE IMMEDIATE 'DROP TABLE variance_log'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE subledger_entries'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE gl_entries'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- GL entries
CREATE TABLE gl_entries (
  entry_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  gl_account     VARCHAR2(30)    NOT NULL,
  amount         NUMBER(15,2)    NOT NULL,
  entry_date     DATE            NOT NULL,
  source_system  VARCHAR2(50),
  CONSTRAINT pk_gl_entries PRIMARY KEY (entry_id)
);

-- Subledger entries
CREATE TABLE subledger_entries (
  entry_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  sub_account    VARCHAR2(30)    NOT NULL,
  amount         NUMBER(15,2)    NOT NULL,
  entry_date     DATE            NOT NULL,
  source_system  VARCHAR2(50),
  CONSTRAINT pk_subledger_entries PRIMARY KEY (entry_id)
);

-- Variance log between GL and Subledger
CREATE TABLE variance_log (
  log_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  gl_entry_id  NUMBER           NOT NULL,
  sub_entry_id NUMBER           NOT NULL,
  variance     NUMBER(15,2)     NOT NULL,
  status       VARCHAR2(20)     DEFAULT 'MISMATCH' NOT NULL,
  log_date     DATE             DEFAULT SYSDATE     NOT NULL,
  CONSTRAINT pk_variance_log PRIMARY KEY (log_id),
  CONSTRAINT fk_var_gl  FOREIGN KEY (gl_entry_id)  REFERENCES gl_entries(entry_id),
  CONSTRAINT fk_var_sub FOREIGN KEY (sub_entry_id) REFERENCES subledger_entries(entry_id),
  CONSTRAINT ck_var_status CHECK (status IN ('MATCHED','MISMATCH'))
);

-- Helpful indexes
CREATE INDEX ix_gl_entries_date  ON gl_entries(entry_date);
CREATE INDEX ix_sub_entries_date ON subledger_entries(entry_date);
CREATE INDEX ix_var_status       ON variance_log(status);
